version: '3.4'

services:
  capitalplacement.api:
    image: ${DOCKER_REGISTRY-}capitalplacementapi
    build:
      context: .
      dockerfile: src/CapitalPlacement.API/Dockerfile
  
  capitalplacement.database:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest