version: '3.4'

services:
  capitalplacement.api:
    image: ${DOCKER_REGISTRY-}capitalplacementapi
    build:
      context: .
      dockerfile: src/CapitalPlacement.API/Dockerfile
    environment:
      Cosmos__ConnectionString: AccountEndpoint=https://capitalplacement.database:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;DisableServerCertificateValidation=True;
    depends_on:
      - capitalplacement.database
  
  capitalplacement.database:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    ports:
      - "8088:8081"